// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtngjyvlakfzolkluzbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bmdqeXZsYWtmem9sa2x1emJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0ODM4MDksImV4cCI6MjA1NDA1OTgwOX0.ijMkvCo0No895rccDUnDTi1jN3YbRDwn71wmv-o3KSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);